<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="Digital_Input" Id="{96ecf1fb-507a-4986-9a07-9744e0d850f9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Digital_Input
VAR_INPUT
	Input		: BOOL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Status" Id="{48516cb1-9761-485e-9dbb-8165f63de4be}">
      <Declaration><![CDATA[PROPERTY PUBLIC Status : BOOL]]></Declaration>
      <Get Name="Get" Id="{b8c0b06c-26a8-4cb1-88a4-f6a471440adb}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Status := Input;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="Digital_Input">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Digital_Input.Status.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>