<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{0ed01888-47ce-42c9-9b1b-67fc9476a6f3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	X_Axis			: AXIS_REF;
	Y_Axis			: AXIS_REF;
	Z_Axis			: AXIS_REF;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>